### ISSUE TITLE
"bad file descriptor, Python" when trying to execute code block

### ISSUE THREAD

**Issue by jaffee** [gregsexton/ob-ipython#1]
Installed manually (package doesn't seem to be on melpa yet?) - I'm on OSX Yosemite and emacs 24.5.1

I found that I had to (require 'ob-python) as well or I would get an error that org-babel-variable-assignments:python was not defined.

test.org file:
```
* top
#+BEGIN_SRC ipython :session mysession :exports both
  def foo(x):
      return x + 9

  [foo(x) + 7 for x in range(7)]
#+END_SRC
```

Hitting C-c C-c inside the source blocks results in:

`*Messages*` buffer:
```
executing Ipython code block...
Sent python-shell-completion-setup-code
Sent python-ffap-setup-code
Sent python-eldoc-setup-code
comint-send-string: Writing to process: bad file descriptor, Python
```

**Comment by racktear** [comment]
@jaffee 

This is what raises the error. 

```elisp
(python-shell-make-comint "ipython console --existing emacs-mysession.json" "Python" nil)
```

the ```python-shell-make-comint``` is part of python.el.

When I run the command ```ipython console --existing emacs-mysession.json``` from the console, I get:

```sh
ValueError: unknown locale: UTF-8
```

Likely that's the reason.

**Comment by racktear** [comment]
@jaffee
Running ```(setenv "LC_CTYPE" "en_US.UTF-8")``` in emacs has fixed the problem for me.
Add it to init.el to fix permanently.

**Comment by jaffee** [comment]
Thanks @racktear - I added `(setenv "LC_CTYPE" "en_US.UTF-8"))` to my init file.

Now I'm getting: 
`*Messages*`
```
executing Ipython code block...
Making python-shell-interpreter local to *Python* while let-bound!
Making python-shell-interpreter-args local to *Python* while let-bound!
Sent python-shell-completion-setup-code
Sent python-ffap-setup-code
Sent python-eldoc-setup-code
comint-send-string: Writing to process: input/output error, Python
```

I'll take a closer look at the `python-shell-make-comint` line later today.

**Comment by gregsexton** [comment]
> I found that I had to (require 'ob-python) as well or I would get an error that org-babel-variable-assignments:python was not defined.

Good catch. Just added this require.

@jaffee, Try `M-x toggle-debug-on-error` and add the trace you get here. Also is there anything interesting in the buffers starting with `*-ob-ipython`?

**Comment by jaffee** [comment]
I needed to `sudo pip install pyzmq`

Relevant debug output for posterity:
`*Messages*` with debug toggled on:
```
Debugger entered--Lisp error: (file-error "Writing to process" "bad file descriptor" #<process Python>)
  process-send-string(#<process Python> "import codecs, os;__pyfile = codecs.open('''/var/folders/yw/d5lm39n95kz79tstt7tkd_b80000gp/T/py614548Oi''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/var/folders/yw/d5lm39n95kz79tstt7tkd_b80000gp/T/py614548Oi''');exec(compile(__code, '''/var/folders/yw/d5lm39n95kz79tstt7tkd_b80000gp/T/py614548Oi''', 'exec'));")
  comint-send-string(#<process Python> "import codecs, os;__pyfile = codecs.open('''/var/folders/yw/d5lm39n95kz79tstt7tkd_b80000gp/T/py614548Oi''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/var/folders/yw/d5lm39n95kz79tstt7tkd_b80000gp/T/py614548Oi''');exec(compile(__code, '''/var/folders/yw/d5lm39n95kz79tstt7tkd_b80000gp/T/py614548Oi''', 'exec'));")
  python-shell-send-string("import codecs, os;__pyfile = codecs.open('''/var/folders/yw/d5lm39n95kz79tstt7tkd_b80000gp/T/py614548Oi''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/var/folders/yw/d5lm39n95kz79tstt7tkd_b80000gp/T/py614548Oi''');exec(compile(__code, '''/var/folders/yw/d5lm39n95kz79tstt7tkd_b80000gp/T/py614548Oi''', 'exec'));" #<process Python>)
  python-shell-send-file("/var/folders/yw/d5lm39n95kz79tstt7tkd_b80000gp/T/py614548Oi" #<process Python> "/var/folders/yw/d5lm39n95kz79tstt7tkd_b80000gp/T/py614548Oi" t)
  python-shell-send-string("def __PYDOC_get_help(obj):\n    try:\n        import inspect\n        if hasattr(obj, 'startswith'):\n            obj = eval(obj, globals())\n        doc = inspect.getdoc(obj)\n        if not doc and callable(obj):\n            target = None\n            if inspect.isclass(obj) and hasattr(obj, '__init__'):\n                target = obj.__init__\n                objtype = 'class'\n            else:\n                target = obj\n                objtype = 'def'\n            if target:\n                args = inspect.formatargspec(\n                    *inspect.getargspec(target)\n                )\n                name = obj.__name__\n                doc = '{objtype} {name}{args}'.format(\n                    objtype=objtype, name=name, args=args\n                )\n        else:\n            doc = doc.splitlines()[0]\n    except:\n        doc = ''\n    try:\n        exec('print doc')\n    except SyntaxError:\n        print(doc)" #<process Python>)
  python-shell-send-setup-code()
  run-hooks(change-major-mode-after-body-hook comint-mode-hook inferior-python-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook comint-mode-hook inferior-python-mode-hook))
  run-mode-hooks(inferior-python-mode-hook)
  inferior-python-mode()
  python-shell-make-comint("ipython console --existing emacs-mysession.json" "Python" nil)
  run-python("ipython console --existing emacs-mysession.json" nil nil)
  ob-ipython--create-repl("mysession")
  (if (string= session "none") (error "ob-ipython currently only supports evaluation using a session.\nMake sure your src block has a :session param.") (ob-ipython--create-driver) (ob-ipython--create-kernel (ob-ipython--normalize-session session)) (ob-ipython--create-repl (ob-ipython--normalize-session session)))
  org-babel-ipython-initiate-session("mysession")
  (let* ((file (cdr (assoc :file params))) (session (cdr (assoc :session params)))) (org-babel-ipython-initiate-session session) (let ((result (ob-ipython--eval (ob-ipython--execute-request (org-babel-expand-body:generic body params (org-babel-variable-assignments:python params)) (ob-ipython--normalize-session session))))) (if result (progn (cond ((and file (string= ... "png")) (ob-ipython--write-base64-string file (cdr ...))) (file (error "%s is currently an unsupported file extension." (f-ext file))) (t (cdr (assoc ... result))))))))
  org-babel-execute:ipython("def foo(x):\n    return x + 9\n\n[foo(x) + 7 for x in range(7)]" ((:comments . "") (:shebang . "") (:cache . "no") (:padline . "") (:noweb . "no") (:tangle . "no") (:exports . "both") (:results . "replace") (:hlines . "no") (:session . "mysession") (:result-type . value) (:result-params "replace") (:rowname-names) (:colname-names)))
  org-babel-execute-src-block(nil)
  org-babel-execute-src-block-maybe()
  org-babel-execute-maybe()
  org-babel-execute-safely-maybe()
  run-hook-with-args-until-success(org-babel-execute-safely-maybe)
  org-ctrl-c-ctrl-c(nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)
```
`*ob-ipython-ob-ipython-driver*`
```
Traceback (most recent call last):
  File "/Users/jaffee/.emacs.d/ob-ipython/driver.py", line 1, in <module>
    from IPython.lib.kernel import find_connection_file
  File "/Library/Python/2.7/site-packages/IPython/lib/kernel.py", line 11, in <module>
    from IPython.kernel.connect import *
  File "/Library/Python/2.7/site-packages/IPython/kernel/__init__.py", line 4, in <module>
    from . import zmq
  File "/Library/Python/2.7/site-packages/IPython/kernel/zmq/__init__.py", line 14, in <module>
    check_for_zmq('2.1.11', 'IPython.kernel.zmq')
  File "/Library/Python/2.7/site-packages/IPython/utils/zmqrelated.py", line 37, in check_for_zmq
    raise ImportError("%s requires pyzmq >= %s"%(required_by, minimum_version))
ImportError: IPython.kernel.zmq requires pyzmq >= 2.1.11

Process ob-ipython-driver exited abnormally with code 1
```

**Comment by jaffee** [comment]
Now I'm getting 
```
executing Ipython code block...
Contacting host: localhost:9988
Code block produced no output.
```

This is for the same code block that's in the README.

**Comment by gregsexton** [comment]
Glad you're slowly getting this resolved. Do you get that error everytime? Or does some code work? You may want to follow issue #5 as it looks like you're no longer alone.

**Comment by gregsexton** [comment]
#5 is resolved now. You probably just need to upgrade IPython. Let me know if this doesn't work for you.

**Comment by jaffee** [comment]
`sudo pip install --upgrade ipython`

ahhhh success! thanks @gregsexton - very excited to use this!

**Comment by ramestica** [comment]
I have installed python 3 and its pattern compatible ipython packages (ubuntu 14.04). Because I heavily depend on python 2.x I cannot just remove 2.7 and, therefore, I have now both flavours. From the shell I must use phyton3 and ipython3 to run them. I have locally changed in ob-ipython.el ob-ipython--kernel-cmd and ob-ipython--kernel-repl-cmd replacing ipython by ipython3. In ob-ipython--create-driver replaced python by python3 (running on linux). Byte compiled.

After all that I'm still having a 'produced no output' issue as shown below. 

Any suggestions? Thanks

executing Ipython code block...
Contacting host: localhost:9988
Code block produced no output.

**Comment by gregsexton** [comment]
ob-ipython works with both python 2 and 3. I personally use it with 2.7 and 3.4. It's *IPython* that you need to upgrade. What version of IPython are you running?

**Comment by ramestica** [comment]
I see. I was really unaware of how ipython versions pairs with python itself. In my ubuntu 14.04 installation I have now ipython and ipython3. The first reports python 2.7.6 and the second 3.4.0, and both report ipython 1.2.1.  I do not think I could update ipython from 1.x up to 3.x by means of standard ubuntu packages. Would you recommend me to try manually installing ipython 3.x somewhere in my file system?

**Comment by gregsexton** [comment]
You can try using pip to install the latest version of IPython. This has worked well for me in the past.

**Comment by ramestica** [comment]
I have used pip to upgrade ipython. Now when I start ipython it says Python 2.7.6 and IPython 3.2.0. Now I correctly see the output of the example code at the beginning of this thread. But when I try to plot something then I get  the exception shown below.

Plotting from ipython started on a shell window works just fine. 

...
-> 2816     ax = gca()
...
TypeError: unbound method __init__() must be called with UserDict instance as first argument (got WeakValueDictionary instance instead)

**Comment by ramestica** [comment]
if I comment out '%matplotlib inline' then I get a floating plot, which is quite better. This means that it just inline figures what's not working for me.
