### ISSUE TITLE
Cannot capture stdout

### ISSUE THREAD

**Issue by julienchastang** [gregsexton/ob-ipython#10]
```
#+begin_src ipython :session :results output
print "Hello, world!"
#+end_src python
```
Yields results in the `ob-ipython-stout` buffer but nothing in the `#+RESULTS:` section

Anyone else seeing this problem?

Thanks again.

**Comment by dfeich** [comment]
I am seeing the exact same. The output is written to the `*ob-ipython-stdout*` buffer, but it is not inserted into the #RESULTS: section.

Not to forget: Thanks for this extremely exciting package! I can't wait to transfer part of my current workflows to ob-ipython!

**Comment by gregsexton** [comment]
This behaviour is correct. The results section contains the result of evaluating the last expression. The print statement does not evaluate to anything and hence no result. From an ipython repl:

    In [2]: print ("hello, world")
    hello, world

    In [3]: "hello, world"
    Out[3]: 'hello, world'

Notice there is no 'out' line after the first 'in'.

The gist is that you should use prints for debugging or capturing out-of-band information and the last statement to 'return' a value.

**Comment by dfeich** [comment]
Dear Greg

The behavior then would be different from all the other babel modules. There the `:results stdout` option will capture all the stdout that is produced during the running of the babel block. Currently it always behaves as if one specified the `:results value` option (the default), which will just return the last value.

In the [manual section](http://orgmode.org/manual/results.html#results) the behavior is documented as follows: 
`output`: The result is the collection of everything printed to STDOUT during the execution of the code block. This header argument places the evaluation in scripting mode. E.g., `:results output`.

It would be great if you could make that change.

Best regards
Derek

**Comment by gregsexton** [comment]
Ah, I understand now. I missed the `:results output` arg before. When output is specified I'll ensure everything is in the results drawer and the stdout buffer isn't shown.

**Comment by gregsexton** [comment]
Just pushed the fix for this. Let me know if it doesn't work for you.

**Comment by dfeich** [comment]
Dear Greg

Thanks... Works perfectly. Only tested today - I was waiting until MELPA
had picked up the change, which took quite some time.
