### ISSUE TITLE
Improve tabular data output representation?

### ISSUE THREAD

**Issue by john2x** [gregsexton/ob-ipython#104]
The default output of tabular data looks like below. A bit hard to read especially with the explicit line break.
<img width="738" alt="oreilly-ml 2017-04-09 21-23-50" src="https://cloud.githubusercontent.com/assets/332885/24837645/63a56048-1d6b-11e7-88b4-521c28a2b47a.png">

Is there an option to not break at ~72 characters? Or better yet, use Org's table features?

**Comment by stonejiajia** [comment]
You can use[tabulate](https://pypi.python.org/pypi/tabulate)
![](http://7xkeje.com1.z0.glb.clouddn.com/Screen%20Shot%202017-04-25%20at%205.33.35%20PM.png)

**Comment by gregsexton** [comment]
Yeah use tabulate. I've added this tip to the readme.
