### ISSUE TITLE
Finding ipykernel >= 5.0?

### ISSUE THREAD

**Issue by jwhendy** [gregsexton/ob-ipython#107]
I'm pretty new to jupyter, but a long user of org-mode/babel for `R`. I'm trying to follow along with requirements, particularly this one:

> IPython kernel (>= 5.0)

I'm on Ubuntu 16.04, which defaults to `python -> python2`. So:
```
$ sudo apt-get install python-pip
$ sudo pip install jupyter
...
Collecting jupyter
  Downloading jupyter-1.0.0-py2.py3-none-any.whl
Collecting ipykernel (from jupyter)
  Downloading ipykernel-4.6.1-py2-none-any.whl (104kB)
    100% |████████████████████████████████| 112kB 777kB/s 

... [console, nbconvert, others download] ...

   IPython 6.0+ does not support Python 2.6, 2.7, 3.0, 3.1, or 3.2.
    When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
    Beginning with IPython 6.0, Python 3.3 and above is required.
```

Alright... let's try `python3`
```
$ sudo apt-get install python3-pip
$ sudo pip3 install jupyter
# [succeeds]
$ pip3 list |grep ipy
ipykernel (4.6.1)
```

Is one supposed to specify the version upon installing? It seems that neither default satisfies the dep. Sorry for the noob question... I'd assumed that just going about installing these today when the info was written < today would automatically have me up to date!

**Comment by Xparx** [comment]
Hi,
I'm no expert either but it looks to me that this is the latest version of ipykernel. I think what is meant is actually ipython (>= 5....). But I'm just guessing.

**Comment by gregsexton** [comment]
Oh yeah this is terrible wording. You need ipython >= 5. Will fix the readme.
