### ISSUE TITLE
tramp support

### ISSUE THREAD

**Issue by cnglen** [gregsexton/ob-ipython#110]
When in tramp, can I call the "python" in remote server using "C-c C-c"?

**Comment by z-n-g-g-u-v-n-f** [comment]
I'm really looking for this, too.
I think right now this is not possible or does anybody get it?

**Comment by heroxbd** [comment]
I think this should be close as an duplicate of Issues #58 and #11.

**Comment by cnglen** [comment]
See Issues #58 and #11.
