### ISSUE TITLE
Multiple blocks/images 

### ISSUE THREAD

**Issue by falematte** [gregsexton/ob-ipython#116]
I use ob-ipython in a very similar way to a mathematica notebook. In order to do this it would be interesting to evaluate all source block in a file and print the output of each of them. In order to do this the image exported by each one should be different. It would be usefull to do this without writing the name of each file...

**Comment by singletS** [comment]
https://github.com/jkitchin/scimax

You may want to look at the scimax starter kit. It provides many features that help org mode behave more like a mma notebook (auto-named output drawers, auto-naming figures, etc.).  Uses a modified version of ob-ipython.

**Comment by gregsexton** [comment]
Didn't see this issue until just now, but very happily and coincidentally, I just added this feature. You don't have to supply a file name any more.
