### ISSUE TITLE
Interactive graphics

### ISSUE THREAD

**Issue by mankoff** [gregsexton/ob-ipython#13]
Is there a way to have graphics not be inline, so that we can work with them interactively?

**Comment by gregsexton** [comment]
What happens if you don't evaluate `%matplotlib inline` (or if you've already evaluated it try evaluating just `%matplotlib`)? This should pop up a window.

**Comment by mankoff** [comment]
Yes that works. Not sure why it didn't seem to work for me before.

**Comment by mankoff** [comment]
Although a new `*ob-ipython-stdout*` buffer pops up with `Using matplotlib backend: MacOSX` which is problematic.

**Comment by gregsexton** [comment]
I don't really view this as an issue. When you run `%matplotlib`, it outputs that message to stdout which ob-ipython displays as always. You only need to run it once to start using interactive graphics. I tend to open a repl using `C-c C-v C-z` and run it there as it's not usually appropriate for it to be a part of my document.

If this doesn't work for you, maybe I could look at supplying an option to disable outputting the stdout?
