### ISSUE TITLE
Unable to use clojure kernel from readme

### ISSUE THREAD

**Issue by dakrone** [gregsexton/ob-ipython#143]
I have ob-ipython set up and working correctly for Python code (thank you very much for this, by the way!), but when I try to use the example of Clojure from the readme:

```
#+BEGIN_SRC ipython :session :kernel clojure
(+ 1 2)
#+END_SRC
```

I end up with the following error:

```
  File "<ipython-input-46-16d0fc7f73b5>", line 1
    (+ 1 2)
         ^
SyntaxError: invalid syntax
```

The readme mentions "You need to have the Jupyter kernel installed and working before you can use this.". I've installed `jupyter` but is there something different I need to install to get other kernels working?

**Comment by gregsexton** [comment]
> I've installed jupyter but is there something different I need to install to get other kernels working?

Yes, you need to install a kernel for each language you want to use. Usually the kernel will also require you install the language's runtime/environment too. Check out this page for a starting point: https://github.com/jupyter/jupyter/wiki/Jupyter-kernels

I recommend installing and confirming this works using the jupyter console on the command line, and then once that's good testing out ob-ipython.

**Comment by dakrone** [comment]
Thanks for the response!
