### ISSUE TITLE
Invalid argument 3 of operation

### ISSUE THREAD

**Issue by isaaczhou** [gregsexton/ob-ipython#147]
Hi try to run it within the ubuntu subsystem on windows 10, got the following error. Looks like it's an lisp error. Any suggestion where it might go wrong? Thanks.

Debugger entered--Lisp error: (error "Invalid argument 3 of operation `call-process-region'")call-process-region("my_list = [1,2,3,4,5]\nmy_list" nil nil nil t nil "--" "/home/isaac/.emacs.d/elpa/ob-ipython-20171203.126/client.py" "--conn-file" "no$apply(call-process-region "my_list = [1,2,3,4,5]\nmy_list" nil nil nil t nil ("--" "/home/isaac/.emacs.d/elpa/ob-ipython-20171203.126/client.py" "--conn-fi$ob-ipython--execute-request("my_list = [1,2,3,4,5]\nmy_list" "none")ob-ipython--execute-sync("my_list = [1,2,3,4,5]\nmy_list" ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . $org-babel-execute:ipython("my_list = [1,2,3,4,5]\nmy_list" ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results .$org-babel-execute-src-block(nil ("ipython" "my_list = [1,2,3,4,5]\nmy_list" ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . v$org-ctrl-c-ctrl-c(nil)call-interactively(org-ctrl-c-ctrl-c nil nil)command-execute(org-ctrl-c-ctrl-c)

**Comment by tbrantseg** [comment]
I have the same error on the Windows 10 ubuntu subsystem.

**Comment by tbrantseg** [comment]
@isaaczhou What is `python-shell-interpreter` set to for you? `(locate-file python-shell-interpreter exec-path)` returned nil for me, and I realized I had an error in my .emacs.
