### ISSUE TITLE
How to create a buffer with ipython session connected?

### ISSUE THREAD

**Issue by zouhx11** [gregsexton/ob-ipython#177]
In fact I want to achieve the same thing in ob-ipython homepage photo: 

https://raw.githubusercontent.com/gregsexton/ob-ipython/master/screenshot.jpg

that is the top middle window.

**Comment by fuxialexander** [comment]
https://github.com/fuxialexander/doom-emacs-private-xfu/blob/master/modules/lang/org-private/%2Bbabel.el

https://github.com/fuxialexander/doom-emacs-private-xfu/tree/master/modules/lang/python

Check out my setup. Sorry that it's under-documented tho...

**Comment by zouhx11** [comment]
thanks a lot
