### ISSUE TITLE
Remove :RESULTS: .... :END:

### ISSUE THREAD

**Issue by benneti** [gregsexton/ob-ipython#200]
In the screenshot of the readme, your results are not wraped in :RESULTS: :END:, how can one achieve this (I searched quiet a bit and did not find anything)?

**Comment by dcherian** [comment]
`:results value`?  There are a bunch of options. Experiment around. This was changed to the drawer form recently so the README probably hasn't been updated

**Comment by benneti** [comment]
thank you, but I think the problem is that I am using the some patches by scimax to include prints in the output and they probably also add this
