### ISSUE TITLE
Working with ipython3

### ISSUE THREAD

**Issue by stephenjbarr** [gregsexton/ob-ipython#23]
What is needed to make ob-ipython work with ipython3. I think i am quite close:

I made the following changes:

```
(defun ob-ipython--kernel-cmd (name)
  (-concat (list "ipython3" "kernel" (format "--IPKernelApp.connection_file=emacs-%s.json" name))
           ob-ipython-kernel-extra-args))

(defun ob-ipython--kernel-repl-cmd (name)
  (list "ipython3" "console" "--existing" (format "emacs-%s.json" name)))

(defun ob-ipython--create-driver ()
  (when (not (process-live-p (ob-ipython--get-driver-process)))
    (ob-ipython--create-process "ob-ipython-driver"
                                (list (locate-file (if (eq system-type 'windows-nt) "python.exe" "python3")
                                                   exec-path)
                                      ob-ipython-driver-path
                                      (number-to-string ob-ipython-driver-port)))
    ;; give driver a chance to bind to a port and start serving
    ;; requests. so horrible; so effective.
    (sleep-for 1)))

```

I also set the following file-local variables in a .org file where I want to use ipython3:

```
  
# Local Variables:
# org-babel-python-command: python3
# python-shell-interpreter: ipython3
# End:

```

When starting work on an ipython notebook, I get the warning:
```
Warning (python): Your `python-shell-interpreter' doesn't seem to support readline, yet `python-shell-completion-native' was t and "ipython3" is not part of the `python-shell-completion-native-disabled-interpreters' list.  Native completions have been disabled locally. 

```

Using this, ob-ipython is able to send start an ipython3 kernel and C-c C-c sends code to it. However, the results are not displayed in the :RESULTS text. However, I can attach to the running session using a console and inspect the variables and they are set based on the code in the org-mode file. What other changes are necessary to make this work with ipython3?

**Comment by gregsexton** [comment]
I'm not really sure what you're trying to accomplish here. It should work with ipython 3 already. Does the ipython binary launch something other than 3 for you?

**Comment by stephenjbarr** [comment]
For me, ipython launches with version 2.7.9, whereas ipython3 launches
with python 3.4.3. I will experiment with some symlinks and see if I can
get it to work.


On Sun, Aug 23, 2015, at 05:18 AM, Greg Sexton wrote:
> I'm not really sure what you're trying to accomplish here. It should
> work with ipython 3 already. Does the ipython binary launch something
> other than 3 for you?


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/gregsexton/ob-ipython/issues/23#issuecomment-133824751

**Comment by alflanagan** [comment]
This may not be just an ob-ipython issue: https://groups.google.com/forum/#!topic/gnu.emacs.help/sz9bvnfstRw

**Comment by gregsexton** [comment]
Yeah, I see this in Emacs 25 generally.
