### ISSUE TITLE
Update link to EIN to https://github.com/millejoh/emacs-ipython-notebook

### ISSUE THREAD

**Issue by millejoh** [gregsexton/ob-ipython#24]
Yes, really. Sorry for being so picky, but you are linking to the 'old' version of EIN. TKF did some amazing work, but his code has not been updated in a long time and only works with IPython 1.0 and earlier. I have taken his hard work and updated it to work with IPython 2.x and beyond.

Thanks - I am really looking forward to trying out ob-ipython. Your comment on org having better markup and organizing features is spot on, and something I wish I had the time to implement in EIN.

**Comment by gregsexton** [comment]
Oh, thanks for pointing this out: I hadn't realised. Merged the PR.
