### ISSUE TITLE
exporting of strings when converting org-mode file.

### ISSUE THREAD

**Issue by kain88-de** [gregsexton/ob-ipython#27]
I'm trying to use the values stored in variables as strings in my floating text. My current approach
for this is.

``` python
#+name print_acf_val
#+begin_src ipython :session :exports none 
    '{:.3f}'.format(acf_time)
#+end_src

The acf time for this process is call_print_acf_val().
```

In latex that gets evaluated to

``` latex
The acf time for this process is ='10.452'=
```

This is not very ideal to me because it looks ugly. I would ideally like that the latex output looks like

``` latex
the acf time for this process is 10.452
```

In fact that is what happens when I use the normal python interpreter in org-mode

``` text
#+LATEX_CLASS: article

# initialize ipython kernel
#+BEGIN_SRC ipython :session :exports none
acf_time = 10.45678
#+END_SRC

#+name: ipython_acf
#+BEGIN_SRC ipython :session :exports none
'{:.3f}'.format(acf_time)
#+END_SRC

#+name: python_acf
#+BEGIN_SRC python :session :exports none
'{:.3f}'.format(acf_time)
#+END_SRC

The acf time in ipython export is call_ipython_acf()

the acf time in python export is call_python_acf()
```

**Comment by fleimgruber** [comment]
@kain88-de I am not able to reproduce this with `ob-ipython` 20170628.558 and `org` 9.0.6.  Over here it works as you were expecting, i.e. a plain `the acf time for this process is 10.452`.

**Comment by kain88-de** [comment]
Might be fixed now. I haven't using ob-ipython in a long while.
