### ISSUE TITLE
Trying to parse HTTP response code in odd buffer

### ISSUE THREAD

**Issue by thoo** [gregsexton/ob-ipython#33]
````
Debugger entered--Lisp error: (error "Trying to parse HTTP response code in odd buffer:  *http localhost:9988*")
  signal(error ("Trying to parse HTTP response code in odd buffer:  *http localhost:9988*"))
  error("Trying to parse HTTP response code in odd buffer: %s" " *http localhost:9988*") ````

**Comment by billbrod** [comment]
I'm having this issue as well, the exact same one as in #22. I just updated my Jupyter and IPython versions to the most recent version (>4 for both) and just installed ob-ipython. During the install, I get the following warnings:

``` elisp
In ob-ipython--execute-request:
ob-ipython.el:203:20:Warning: reference to free variable
    `url-http-end-of-headers'

In ob-ipython--inspect-request:
ob-ipython.el:264:20:Warning: reference to free variable
    `url-http-end-of-headers'
```

When I try to run one of the example blocks, I get the following messages, just like #22. Is this another version issue with a recent update of jupyter or ipython?

``` elisp
executing Ipython code block...
Making python-shell-interpreter local to *Python* while let-bound!
Making python-shell-interpreter-args local to *Python* while let-bound!
Sent python-shell-completion-setup-code
Sent python-ffap-setup-code
Sent python-eldoc-setup-code
Contacting host: localhost:9988
url-http-parse-response: Trying to parse HTTP response code in odd buffer:  *http localhost:9988*
```

**Comment by gregsexton** [comment]
Just run in to this issue myself on a new laptop. Once I figure it out I'll let you know.

**Comment by gregsexton** [comment]
The problem for me is the python binary that is being used. I used pip to install the necessary modules but the system python (/usr/bin/python) can't seem them. /usr/local/bin/python can. Now to figure out how to make emacs use the second python...

**Comment by gregsexton** [comment]
(setq python-shell-interpreter "/usr/local/bin/python")

Solved all of my problems.

Let me know if this fixes your problems or at least gets you on track to a fix.

**Comment by Xparx** [comment]
I'm just going to add a small note here that might help someone.
I had the same issues but switching from `ipython` to just `python` as `python-shell-interpreter` worked, however for some reason the `notebook` package was not installed with jupyter or ipython for me by default and it spit out the same error for that.
`pip install notebook` fixed that for me.
This is not spelled out in the dependencies probably because it should be obvious but it was a bit of a _got ya_ moment for me.

**Comment by adamthompson922** [comment]
I'm having troubles with this currently. I don't have any installation at `/usr/local/bin/python`. 

I have `/usr/bin/python` and `/usr/bin/python3` as my Python installation binaries.

Can you elaborate on how you solution fixes the problems greg? Thanks.

**Comment by cicerojones** [comment]
The above @Xparx  reminder to `pip install notebook` seemed to solve this problem for me too.

Using ipython 4.2.0 with elpy, I no longer get the HTTP response error, but do get a warning about not supporting readline etc.:
> Native completions have been disabled locally. 

which does not appear when elpy is not enabled (this may be some other problem in my configuration). 
Take it for what it's worth--which may not be much!

**Comment by billbrod** [comment]
The fix of setting `python-shell-interpreter` works for me. I use anaconda, so adding the command `(setq python-shell-interpreter "~/anaconda/bin/python")` worked for me.

**Comment by gregsexton** [comment]
RC: #80 #78
