### ISSUE TITLE
localhost error without debugging message

### ISSUE THREAD

**Issue by LQShen** [gregsexton/ob-ipython#34]
I got the following error when running ob-ipython. 

Debugger entered--Lisp error: (error "localhost/9988 System error")
make-network-process(:name "localhost" :buffer #<buffer  *url-http-temp*> :host "localhost" :service 9988 :nowait t)
  open-network-stream("localhost" #<buffer  *url-http-temp*> "localhost" 9988 :type plain :nowait t)
  byte-code("\306\211\n\307>\203$\n\310=\203\311\312\f
\313\n\314\315\316\317\"&\202Y\n\320=\2034\321\f
$\202Y\n\322=\203D\323\f
$\202Y\n\324=\203T\325\f
$\202Y\326\327\"*\306\207" [coding-system-for-write coding-system-for-read gw-method name buffer host binary (tls ssl native) native plain open-network-stream :type :nowait featurep make-network-process (:nowait t) socks socks-open-network-stream telnet url-open-telnet rlogin url-open-rlogin error "Bad setting of url-gateway-method: %s" service url-gateway-method conn] 11)
  url-open-stream("localhost" #<buffer  *url-http-temp*> "localhost" 9988)
  url-http-find-free-connection("localhost" 9988)
  url-http([cl-struct-url "http" nil nil "localhost" 9988 "/execute/default" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil))
  url-retrieve-internal("http://localhost:9988/execute/default" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil) nil nil)
  url-retrieve("http://localhost:9988/execute/default" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] nil nil nil)
  url-retrieve-synchronously("http://localhost:9988/execute/default")
  ob-ipython--execute-request("%matplotlib inline\nimport matplotlib.pyplot as plt\nimport numpy as np" "default")
  org-babel-execute:ipython("%matplotlib inline\nimport matplotlib.pyplot as plt\nimport numpy as np" ((:comments . "") (:shebang . "") (:cache . "no") (:padline . "") (:noweb . "no") (:tangle . "no") (:exports . "code") (:results . "replace") (:hlines . "no") (:session) (:result-type . value) (:result-params "replace") (:rowname-names) (:colname-names)))
  org-babel-execute-src-block(nil)
  org-babel-execute-src-block-maybe()
  org-babel-execute-maybe()
  org-babel-execute-safely-maybe()
  run-hook-with-args-until-success(org-babel-execute-safely-maybe)
  org-ctrl-c-ctrl-c(nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)

In emacs message buffer, I got 
contacting host : localhost:9988 
Entering debugger 

No error output for ob-ipython-driver 
No error output for ipython (jupyter console 4.0.3)

I run ubuntu 14.04 with emacs 24.5. I installed ob-ipython from MELPA and pointed the load path in emacs init file. I also have tornador installed. 

The error message contains very little information. I searched around but could not find a thread for similar issue. 

appreciate input.

**Comment by gregsexton** [comment]
Please check that you have all the correct dependencies as described in the readme file.

**Comment by LQShen** [comment]
Many thanks for the instruction. 

Here is what I have in my init.el file. 

------------------------------------------------------------------------------
(add-to-list 'load-path "/path/to/elpa/ob-ipython-20151010.307")
(add-to-list 'load-path "/path/to/elpa/dash-20151021.113")
(add-to-list 'load-path "/path/to/elpa/dash-functional-20150828.413")
(add-to-list 'load-path "/path/to/elpa/s-20150924.406")
(add-to-list 'load-path "/path/to/elpa/f-20150605.927")

(require 'ob-ipython)
------------------------------------------------------------------------------

I also checked ipython, jupyter, and tornado on my system. 

Metadata-Version: 1.1
Name: tornado
Version: 4.3

Metadata-Version: 2.0
Name: ipython
Version: 4.0.1

Metadata-Version: 2.0
Name: jupyter
Version: 1.0.0

I can lauch juypter-notebook on a web browser successfully. 

I can also initiate jupyter-console on my terminal.
I also found jupyter_client folder in
/usr/local/lib/python2.7/dist-packages/jupyter_client.

I tried pip install jupyter_client --upgrade and got the message that
"Requirement already satisfied".

It looks to me I have all the dependencies installed.

-----------------------------
ob-ipython readme
-----------------------------
First, you need IPython

In version 4.0, IPython transitioned from a monolithic architecture to
being just one of the kernels supported by the more generic Jupyter
application framework. Beginning with version 4.0 of the IPython kernel,
the Jupyter console application is actually responsible for the REPL
interface. Therefore, depending on the selected or available software,
the appropriate branch of this repository should be selected.

If unsure, use master and an IPython install of 4.0 or greater.

master branch for Jupyter with IPython kernel >= 4.0

Before installing, you’ll need Jupyter (>= 1.0) and the IPython kernel
(>= 4.0) installed and working. You will also need Tornado and the
Jupyter console and client (jupyter_console, jupyter_client) libraries.

ipython3 branch for IPython >=3.0 && < 4.0

If you’re on IPython 3, you can use the ipython3 branch of this
repository. You will also need the Tornado and PyZMQ libraries. These
libraries are usually installed as dependencies of the ipython notebook.

Install the Emacs plugin

This package is now in MELPA. I recommend installing from there.

For manual installation, you’ll need the following elisp dependencies
first:

https://github.com/magnars/dash.el
Including dash-functional
https://github.com/magnars/s.el
https://github.com/rejeep/f.el
Then just drop this somewhere in your load path and (require
'ob-ipython).
-----------------------------

Many thanks for further directions.

sincerely,

Longzhu 


Greg Sexton <notifications@github.com> @ 2015-11-29 04:37 EST:

> Please check that you have all the correct dependencies as described in
> the readme file.
> &mdash;
> Reply to this email directly or view_it_on_GitHub.

-- 
Longzhu Shen

**Comment by gregsexton** [comment]
Have you installed jupyter_console and jupyter_client?
