### ISSUE TITLE
ob-ipython installed but no functions available

### ISSUE THREAD

**Issue by endrebak** [gregsexton/ob-ipython#36]
According to the `ob-ipython` menu in [paradox's](https://github.com/Malabarba/paradox) `paradox-list-packages`:

```
ob-ipython is an installed package.

     Status: Installed in `~/.emacs.d/elpa/ob-ipython-20151010.307/' (unsigned).
    Archive: n/a
    Version: 20151010.307
   Requires: s-1.9.0, dash-2.10.0, dash-functional-1.2.0, f-0.17.2, emacs-24
    Summary: org-babel functions for IPython evaluation
   Homepage: http://www.gregsexton.org
   Keywords: literate programming reproducible research 
    Other versions: 20151010.307 (melpa).
```

Still, when I use `M-x` no `ob-ipython` related functions show up. And when I begin typing `ob-ipython` in a elisp buffer, no functions show up. Furthermore, this happens: https://github.com/gregsexton/ob-ipython/issues/35 . This must mean that the package is not properly installed in some way.

Where can I begin to debug this?

**Comment by gregsexton** [comment]
What happens if you `(require 'ob-ipython)`?

**Comment by endrebak** [comment]
The very same. Closing this since I am just using ein instead.

If sb else experiences the same I'm sure they'll reopen.

Thanks for the package btw.
