### ISSUE TITLE
make client process fails on WIndows 7 

### ISSUE THREAD

**Issue by ajsteven130** [gregsexton/ob-ipython#4]
Hello,

First, thanks for the awesome package. I am using Emacs 24.5 on Windows 7 with Python 3.4 and Ipython 3.1.0.

I installed ob-ipython from master (it does not appear to be on melpa yet), and I have all of the dependencies installed.

When running an ipython block, I get the following messages and no output:

executing Ipython code block...
Contacting host: localhost:9988
open-network-stream: make client process failed: connection refused, :name, localhost, :buffer, #<killed buffer>, :host, localhost, :service, 9988, :nowait, nil

Executing does create a REPL buffer and a kernel buffer.
 
Edit - here is the backtrace from Emacs:

Debugger entered--Lisp error: (file-error "make client process failed" "connection refused" :name "localhost" :buffer #<buffer  *url-http-temp*> :host "localhost" :service 9988 :nowait nil)
  make-network-process(:name "localhost" :buffer #<buffer  *url-http-temp*> :host "localhost" :service 9988 :nowait nil)
  open-network-stream("localhost" #<buffer  *url-http-temp*> "localhost" 9988 :type plain :nowait nil)
byte-code . . . 
 url-open-stream("localhost" #<buffer  *url-http-temp*> "localhost" 9988)
  url-http-find-free-connection("localhost" 9988)
  url-http([cl-struct-url "http" nil nil "localhost" 9988 "/execute/default" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil))
  url-retrieve-internal("http://localhost:9988/execute/default" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil) nil nil)
  url-retrieve("http://localhost:9988/execute/default" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] nil nil nil)
  url-retrieve-synchronously("http://localhost:9988/execute/default")
  (set-buffer (url-retrieve-synchronously (format "http://localhost:%d/execute/%s" ob-ipython-driver-port name)))
  (save-current-buffer (set-buffer (url-retrieve-synchronously (format "http://localhost:%d/execute/%s" ob-ipython-driver-port name))) (if (>= (url-http-parse-response) 400) (ob-ipython--dump-error (buffer-string)) (goto-char url-http-end-of-headers) (let ((json-array-type (quote list))) (json-read))))
  (let ((url-request-data code) (url-request-method "POST")) (save-current-buffer (set-buffer (url-retrieve-synchronously (format "http://localhost:%d/execute/%s" ob-ipython-driver-port name))) (if (>= (url-http-parse-response) 400) (ob-ipython--dump-error (buffer-string)) (goto-char url-http-end-of-headers) (let ((json-array-type (quote list))) (json-read)))))
  ob-ipython--execute-request("from matplotlib import pyplot as plt\nimport numpy as np\nimport pandas as pd\n\n%matplotlib inline" "default")
  (ob-ipython--eval (ob-ipython--execute-request (org-babel-expand-body:generic body params (org-babel-variable-assignments:python params)) (ob-ipython--normalize-session session)))
  (let ((result (ob-ipython--eval (ob-ipython--execute-request (org-babel-expand-body:generic body params (org-babel-variable-assignments:python params)) (ob-ipython--normalize-session session))))) (if result (progn (cond ((and file (string= (f-ext file) "png")) (ob-ipython--write-base64-string file (cdr (assoc ... result)))) (file (error "%s is currently an unsupported file extension." (f-ext file))) (t (cdr (assoc (quote text/plain) result)))))))
  (let* ((file (cdr (assoc :file params))) (session (cdr (assoc :session params)))) (org-babel-ipython-initiate-session session) (let ((result (ob-ipython--eval (ob-ipython--execute-request (org-babel-expand-body:generic body params (org-babel-variable-assignments:python params)) (ob-ipython--normalize-session session))))) (if result (progn (cond ((and file (string= ... "png")) (ob-ipython--write-base64-string file (cdr ...))) (file (error "%s is currently an unsupported file extension." (f-ext file))) (t (cdr (assoc ... result))))))))
  org-babel-execute:ipython("from matplotlib import pyplot as plt\nimport numpy as np\nimport pandas as pd\n\n%matplotlib inline" ((:comments . "") (:shebang . "") (:cache . "no") (:padline . "") (:noweb . "no") (:tangle . "no") (:exports . "both") (:results . "file replace") (:hlines . "no") (:session) (:file . "./tmp/image.png") (:result-type . value) (:result-params "file" "replace") (:rowname-names) (:colname-names)))
  org-babel-execute-src-block(nil)
  org-babel-execute-src-block-maybe()
  org-babel-execute-maybe()
  org-babel-execute-safely-maybe()
  run-hook-with-args-until-success(org-babel-execute-safely-maybe)
  org-ctrl-c-ctrl-c(nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)

**Comment by gregsexton** [comment]
I'll take a look as soon as possible.

**Comment by ajsteven130** [comment]
Thanks very much. I tried going through the code, but I could not find the problem (which is not suprising!). If you need any other information, or if there is anything else I can do to help, just let me know.

**Comment by ElliotJH** [comment]
Running driver.py manually in a console outside of Emacs is a workaround. (I have this same issue)

**Comment by ajsteven130** [comment]
Yes! the workaround from ElliotJH works for me!

**Comment by gregsexton** [comment]
Hmm looks like there's a bug in how I run up the driver.py code. Probably an assumption that doesn't hold true on windows. I don't have a windows machine I'm afraid so I can take a guess but may need some help testing.

**Comment by ElliotJH** [comment]
Happy to help test. Would love to use this on Windows.

**Comment by gregsexton** [comment]
If you do `C-h v ob-ipython-driver-path` what value does this variable have? I suspect the logic I have that resolves the path to the python script doesn't work.

**Comment by ajsteven130** [comment]
for me, `ob-ipython-driver-path` points to the driver.py file in the directory I cloned from github, "c:/Users/A*******/.emacs.d/ob-ipython-master/driver.py"

**Comment by ajsteven130** [comment]
it seems that Windows has a problem with either the `(locate-file "python" exec-path)`  function in `ob-ipython--create-driver`or the `start-process` function  in  `ob-ipython--create-process`. 

From a backtrace, it seems that `(locate-file "python" exec-path)` is returning `nil` and I cannot seem to run `start-process` manually.

everything works if I overwrite `ob-ipython--create-driver` to use `start-process-shell-command` with:

```
(defun ob-ipython--create-driver ()
  (when (not (process-live-p (ob-ipython--get-driver-process)))
    (start-process-shell-command "ob-ipython-driver" "*ob-ipython-driver*" "python c:/Users/A******/.emacs.d/ob-ipython-master/driver.py 9988")
    ;; give driver a chance to bind to a port and start serving
    ;; requests. so horrible; so effective.
    (sleep-for 1)))
```

this is a hack that is way more horrible than using `sleep-for` :)

Obviously, I could use the variables for the port and the path. . . 

I could prepare a pull request that overwrites this function if emacs is running on windows or defines a new function for windows users, but I think there must be a better solution that is less hacky.

**Comment by ElliotJH** [comment]
Points to my copy of `driver.py` in `%APPDATA%/.emacs.d/ob-ipython/driver.py` as expected.

As @ajsteven130 says, `(locate-file "python" exec-path)` returns `nil` for me.

**Comment by ajsteven130** [comment]
changing `(locate-file "python" exec-path)` to `(locate-file "python.exe" exec-path)` makes everything work. I will submit a PR that sets a new variable `ob-ipython-python-executable-search-string` to "python.exe" in `(system-type)` returns "windows-not". Someone else will need to be sure that it still works for other systems.

**Comment by gregsexton** [comment]
Ah, of course `.exe`! Let me take a look at the PR.
