### ISSUE TITLE
No org-babel-execute function for ipython

### ISSUE THREAD

**Issue by Plancalkuele** [gregsexton/ob-ipython#43]
Hi there,
I'm trying to set up ob-ipython under spacemacs.

I installed ipython3, python3-tornado, python3-zmq via sudo apt-get install

The packages dash, s, f and ob-ipython are loaded the spacemacs way:
`(setq dotspacemacs-additional-packages '(dash s f ob-ipython)`

By applying this way of loading packages in spacemacs no configuration will be associated with those packages. So either I have to create a private layer for ob-ipython in spacemacs or I can define the necessary configuration within dotspacemacs/user-config.

What do I have to configure or tell org-babel when I get the following message when I try to evaluate a SRC block?: _No org-babel-execute function for ipython_

**Comment by osdf** [comment]
Can reproduce this behaviour. Also see #36. If one adds the definition mentioned in #35 then execution works, but no ipython kernel is started but a standard python instance. In this case, C-c C-v C-z does not work.

**Comment by osdf** [comment]
Adding ```'org-babel-load-languages '((ipython . t)))``` starts now an ipython process, and also makes C-c C-v C-z work.

**Comment by Plancalkuele** [comment]
This is the what I put in ~/.spacemacs:
`(defun dotspacemacs/user-config ())
(with-eval-after-load 'org
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((ipython . t)))
  )`

Evaluating a python code block with C-c C-c I get the following response:
`Trying to parse HTTP response code in odd buffer: *http localhost:9988*-676839`

C-c C-v C-z works. The command starts a new buffer with an ipython shell in inferior python-mode.

**Comment by osdf** [comment]
In your ```with-eval...``` block i also have:

```
  (setq org-confirm-babel-evaluate nil)
  (setq org-export-babel-evaluate nil)
  (setq org-startup-indented t)
  ;; Update images from babel code blocks automatically
  (add-hook 'org-babel-after-execute-hook 'org-display-inline-images)
  (setq org-src-fontify-natively t)
  (setq org-src-tab-acts-natively t)
```
Does that help?

**Comment by Plancalkuele** [comment]
Nope...unfortunately your suggestion doesn't solve the problem.
I still get the following message:
 `Trying to parse HTTP response code in odd buffer: *http localhost:9988*-676839`

**Comment by osdf** [comment]
I'm using anaconda as my python distribution. Maybe some stuff for ipython usage is simply missing?

**Comment by Plancalkuele** [comment]
Yes, your're right. The actual question has been answered.
The solution was to put:

```
(defun dotspacemacs/user-config ())

(with-eval-after-load 'org
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((ipython . t)))
  )
```

in ~/.spacemacs

I will open up another issue with the 'Trying to parse HTTP response code in odd buffer: *http localhost:' problem.
