### ISSUE TITLE
Multiple plots output

### ISSUE THREAD

**Issue by nasseralkmim** [gregsexton/ob-ipython#48]
Is there any way to display multiple inline images output in the result block?

**Comment by gregsexton** [comment]
No. The output is a single file path. If you want multiple images you need to either generate a single image that combines them (this is usually easy to do with grids of matplotlib charts) or use multiple source blocks.

**Comment by khourhin** [comment]
Here is an alternative apparently:
[http://kitchingroup.cheme.cmu.edu/blog/2017/01/29/ob-ipython-and-inline-figures-in-org-mode/](http://kitchingroup.cheme.cmu.edu/blog/2017/01/29/ob-ipython-and-inline-figures-in-org-mode/)
