### ISSUE TITLE
Code block produced no output

### ISSUE THREAD

**Issue by gperaza** [gregsexton/ob-ipython#5]
When executing a code block I get:
Code block produced no output.
in the minibuffer and the results remain blank.

The code is evaluated, but no output is produced, I have tried the the examples and my own code blocks with a minimal configuration file.

**Comment by gregsexton** [comment]
Can you paste a block of code you're trying that gives you this problem?

**Comment by racktear** [comment]
@gregsexton I have this problem too. The following code block leads to the mentioned problem:
```
#+BEGIN_SRC ipython :session
    123 + 456
#+END_SRC
```

Though, if I do this:
```elisp
(ob-ipython--execute-request "print 123 + 456" "mysession2")
```
In the 'Messages' buffer, I see the list that contains "579" in data.

**Comment by gperaza** [comment]
The example provided by racktear is accurate. I'm using emacs 24.5 on Ubuntu 14.04. Ipython version 2.3.0.

**Comment by racktear** [comment]
I confirm that upgrading ipython to 3.1 has fixed the problem.

**Comment by gregsexton** [comment]
Ah great to hear. Just checked the machines I've used to test this and I'm 3.1 everywhere.

> The message protocol has been updated from version 4 to version 5. Adapters are included, so IPython frontends can still talk to kernels that implement protocol version 4.

Found this in the IPython 3.0 release notes. Looks like 3.0 is a minimum requirement. Will update the readme. Thanks for your help all.
