### ISSUE TITLE
interpreter python version 2 on linux

### ISSUE THREAD

**Issue by tntdynamight** [gregsexton/ob-ipython#51]
in melpa ob-ipython 20160305.843, opening ipython blocks in org-babel throws me into ipython with python 2 instead of python3. 

python-mode opens correctly with anaconda ipython with python 3 after having set 
`  (setq python-shell-interpreter "~/anaconda3/bin/ipython3")`
, and ob-ipython connects to it when previously opened by python-mode manually. 

I run on ubuntu with ipython and python installed; anaconda version is on my path (shell opens anaconda ipython by default). 

I thought after Issue [32](https://github.com/gregsexton/ob-ipython/issues/32), python-shell-interpreter was used. 

I tried adding any of these, but none change it:
```
  (setq python-shell-exec-path "~/anaconda3/bin")
  (setq python-shell-interpreter "~/anaconda3/bin/ipython3")
  (setq org-babel-python-command "~/anaconda3/bin/ipython3")
```

Am I overlooking something?

**Comment by gregsexton** [comment]
#78

**Comment by gregsexton** [comment]
`(setq python-shell-interpreter "~/anaconda3/bin/ipython3")` should have worked.

Maybe you needed `(setq python-shell-interpreter (expand-file-name "~/anaconda3/ibn/ipython3"))`?

**Comment by tntdynamight** [comment]
Even so, When opening a source-code block (C-c C-v z), I get thrown into the wrong python; once in a code buffer if I close the Python process and open a new one via (C-c C-p) it gives me the correct anaconda python. Maybe it's an org-mode function calling it wrongly? Sorry, I don't know where to look.

**Comment by gregsexton** [comment]
Which version of Emacs? People have been complaining that this is generally broken in 25.x

**Comment by tntdynamight** [comment]
This is on: GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7)
