### ISSUE TITLE
Python Warnings upon Startup

### ISSUE THREAD

**Issue by dschrempf** [gregsexton/ob-ipython#55]
Hello, when I execute a code block, I get the following warnings in my python session:

    [TerminalIPythonApp] WARNING | Subcommand `ipython console` is deprecated and will be removed in future versions.
    [TerminalIPythonApp] WARNING | You likely want to use `jupyter console`... continue in 5 sec. Press Ctrl-C to quit now.

**Comment by gregsexton** [comment]
#59
