### ISSUE TITLE
Inline Math and Dark Background

### ISSUE THREAD

**Issue by dschrempf** [gregsexton/ob-ipython#56]
Hello,

I use Emacs with a dark background.  Inline matplotlib plots by default have white background which is OK.  However, the tick labels and axes labels have black facecolor and are transparent.  I.e., the facecolor and the backgroundcolor is dark and they are not readable.  Is there a workaround, how I can change either the transparency of this region, or the facecolor?

Thanks,
Dominik

**Comment by girip** [comment]
You can change the background of the matplotlib figures using face color option when invoking the plot. 
For example I use as a fix for this issue

fig, ax = plt.subplots(facecolor='w')

**Comment by dschrempf** [comment]
OK thank you, that is a good workaround!

**Comment by joinvim** [comment]
Use:
```python
matplotlib.rcParams['patch.facecolor']  = '#8CD0D3'
```
or  add this string in file .matplotlibrc

**Comment by joinvim** [comment]
Close this ticket, its not problem of ob-ipython.
