### ISSUE TITLE
We should be calling 'jupyter console' not 'ipython console'

### ISSUE THREAD

**Issue by adamthompson922** [gregsexton/ob-ipython#59]
When I try running `C-c C-c` for a source code block, I get `Process Python not running`.

I have found two ways around this:

1) Run `M-x run-python` first.

2) Switch the following in `ob-ipython.el` (a trick I got from a redditor on /r/emacs).

```
(defun ob-ipython--kernal-repl-cmd (ameE)
  (list "ipython" "console" "--existing" (format "emacs-%s.json" name)))
```

for

```
(defun ob-ipython--kernal-repl-cmd (ameE)
  (list "jupyter" "console" "--existing" (format "emacs-%s.json" name)))
```

Any idea why this works? Both solutions feel wrong because in 1) I have to run a command every time and 2) I have to modify the source code which ruins any chance of upgrading potentially.

**Comment by fanpeng-kong** [comment]
I remember I used to have this problem too, but I definitely did not change any source code in ob-ipython. Can you please try `(setq python-shell-interpreter "/usr/local/bin/python")' and see how it goes? Maybe change to your preferred python interpreter.

**Comment by singletS** [comment]
@adamthompson922 option 2) in your post above updates ob-ipython to start the jupyter notebook server which then manages code blocks intended for an IPython kernel.  IPython no longer serves notebooks directly, so the command line and args in ob-ipython.el are obsolete.  Hopefully, @gregsexton can include the fix soon. This may help with #63, too.

**Comment by AlejandroCatalina** [comment]
I'm also running into this issue. In my case doing run-python before executing a source block is not enough, the *Python* buffer tells me 

```[ZMQTerminalIPythonApp] CRITICAL | Could not find existing kernel connection file emacs-default.json```

Which is pretty obvious but I couldn't find the code that generates that file.

Any points? Thansk!

**Comment by osdf** [comment]
Just for completeness, I think the referenced reddit thread is this one: https://www.reddit.com/r/emacs/comments/4h7k37/cant_get_obipython_running/ (I haven't tried out, if everything works with these changes).

**Comment by gregsexton** [comment]
Changed the default command name from ipython to jupyter. Should fix this.
