### ISSUE TITLE
Buffer blah.org has no process (support process-live-p in 24.3)

### ISSUE THREAD

**Issue by brianmingus** [gregsexton/ob-ipython#6]
I am new to org mode so I am possibly doing something very basic wrong. Do you know why I get this error when I Ctrl-c,c my python code?

**Comment by gregsexton** [comment]
Where do you run `C-c C-c`? You need to press it with the point (cursor) in the src block in the org buffer not the python buffer that is opened when you press `C-c '`. Does this help?

**Comment by brianmingus** [comment]
Yes that's what I'm doing. How does this thing figure out where ipython is? From my path?

**Comment by brianmingus** [comment]
I am also running an instance of ipython notebook. I don't see driver.py running on this system...

**Comment by gregsexton** [comment]
Yeah it looks for ipython on your path. I'm going to need more info to debug this one.

What OS are you on? Emacs version? Python version? IPython version?

Can you paste the traceback when the error occurs (you'll need to `M-x toggle-debug-on-error`).

What buffers do you have that begin with `*ob-ipython`? Do any of them contain errors that look suspicious?

**Comment by gregsexton** [comment]
Are you on windows? You may be having the same problem as #4

**Comment by frankieliu** [comment]
Getting same problem in linux, I checked where it was breaking in debug, and then I ran each of these lines by hand:

-- Stops on (if (not (process-live-p (ob-ipython--get-driver-process))) 

(ob-ipython--create-process "ob-ipython-driver" (list (locate-file "python" exec-path) ob-ipython-driver-path (number-to-string ob-ipython-driver-port)))

-- this does create a process and (ob-ipython--get-driver-process) lists it, sometimes
   I do get past this point, and (process-live-p (ob-ipython--get-driver-process)) returns with (run open listen connect stop), but on C-c again, I sometimes keep getting stuck at the same if statement 
-- sometimes, it got past the first if statement, then it blocked on the next if for the kernel, then I ran the following

(ob-ipython--create-process (format "kernel-%s" name) (ob-ipython--kernel-cmd name))

-- Finally got three buffers: the driver buffer, the kernel buffer, and the Python buffer

But after running these by hand I get stuck somewhere else.  So it seems that the creation of the processes has a problem when running through the code (C-c) (why?), but it seems to kick in fine when done by hand ( I tried to add more sleep time, but that didn't do anything ).

Skip below as it is a different problem now.
----------

Then it seems to kick in, however I am getting problems with proxy: in *ob-ipython-debug*  I get
HTTP/1.1 502 cannotconnect
Content-Type: text/html
Cache-Control: no-cache
Content-Length: 2683
Proxy-Connection: Close
...
 <td class="contentData">
      The proxy could not connect to the destination in time. Please verify the site you are attempting to access and retry.
    </td>
...
 <td class="infoData">
      <b>URL: </b><script type="text/javascript">break_line("http://localhost:9988/execute/mysession");</script><br />
    </td>

It seems that my proxy is blocking 9988, but I am not sure, is there another way to debug this problem?

**Comment by julienchastang** [comment]
Thanks for taking this on. I am seeing the same problem:

process-live-p: Buffer example1.org has no process

It would be great to get this to work.

**Comment by julienchastang** [comment]
I spent a while digging into this. First, make sure you have a recent version pyzmq (pip install). Secondly, `(process-live-p nil)` returns `(run open listen connect stop)`, which seems very odd (bug in `process-live-p`?). If you simply remove the call to `process-live-p` it, sort of, fixes the issue. Actually, issuing C-c C-c the first time will fail, but subsequent times it will work. This project now works for me (on my fork, if interested), though I am having trouble in-lining images, mysteriously. Thanks again.

**Comment by gregsexton** [comment]
Which version of Emacs are you guys running? `(process-live-p nil)` returns `nil` for me.

**Comment by julienchastang** [comment]
`GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7) of 2014-03-07 on lamiak, modified by Debian`
`Org-mode version 8.2.10 (8.2.10-41-g42228a-elpa @ /root/.emacs.d/elpa/org-20150608/)`

`Emacs 24.3.1` is the latest version of emacs available via the ubuntu package manager, AFAIK.

**Comment by frankieliu** [comment]
I have the exact same version.

**Comment by gregsexton** [comment]
You don't need ipython-notebook. It requires a superset of the dependencies that ob-ipython does, so if you already had it installing this would have been easier.

It sounds like 24.3 either has a bug or the behaviour changed as of 24.4. I've tested this on both 24.4 and 24.5 and it works correctly. I'll see what I can do to support 24.3 but you may wish to consider upgrading Emacs. If apt doesn't have a newer version, building from source in my experience is very painless. You'll already have all the necessary dependencies on your system as you've installed 24.3.

**Comment by brianmingus** [comment]
Installing the latest emacs 24.5.1 on Ubuntu Utopic is not that easy. You will need:

- sudo apt-get install libxaw7-dev libtiff-dev libgif-dev
- build / install libpng 1.6 from source
- sudo apt-get remove emacs
- sudo apt-get autoremove # crucial to fully get rid of emacs
- finally, build and install emacs

Then you will get the following error when pressing Ctrl-c,c which I have no idea how to debug. I would definitely put a warning up that this requires the bleeding edge release of emacs. I think only a very small number of people are using that on linux.

![screenshot 2015-06-14 at 10 27 11 am](https://cloud.githubusercontent.com/assets/3188728/8149430/372120b8-1280-11e5-952c-5989bc38acc9.png)

**Comment by brianmingus** [comment]
Ok this is working now if you install ob-ipython from melpa. 

I have never used org mode before, but my python code is not in python-mode.

**Comment by julienchastang** [comment]
This also seems to be a problem with Ubuntu. Emacs 24.3 is more than two years old, and we are now on 24.5. Anyone have involvement with the Ubuntu community to have them update emacs?

**Comment by thorrr** [comment]
Just submitted a pull request to fix this problem.  I'm on 24.3 still because the advice syntax completely changed in 24.4 and broke a bunch of my stuff.  Too lazy to port to the new syntax just yet.

**Comment by gregsexton** [comment]
Just merged @thorrr's PR. Hopefully this issue is now fixed. Feel free to reopen if you still have problems.
