### ISSUE TITLE
No output in REPL

### ISSUE THREAD

**Issue by joonro** [gregsexton/ob-ipython#73]
Hi,

Thanks for the awesome package. I installed it from melpa and I'm using it with GNU Emacs 25.0.94.2 (x86_64-w64-mingw32), and org 8.3.4. 

When I do `c-c c-v c-z` in a ipython source code block, REPL opens and it seems to work, except that I'm not getting any output. For example, it looks like this:

```python
[TerminalIPythonApp] WARNING | Subcommand `ipython console` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter console` in the future

In [2]: 

In [2]: print(1)

In [3]: 
```

I'm not sure if I'm doing something wrong? Any help would be great!

**Comment by joinvim** [comment]
Don't use Emacs 25, it's not release, so not tested. I have not work Haskell REPL on emacs 25.

**Comment by joonro** [comment]
I just downgraded emacs to 24 and it now works well. Thank you!
