### ISSUE TITLE
Kernel did not respond warning

### ISSUE THREAD

**Issue by pwt-nf** [gregsexton/ob-ipython#86]
Hi,

I'm on OSX El Capitan. Followed install instructions using MELPA

Upon `C-c C-c` on the following:

`#+BEGIN_SRC ipython :session                                                                                                                                                                    
import statsmodels.api as sm
import pgc_utils as ut
import pandas as pd
import numpy as np
from tabulate import tabulate
#+END_SRC`

and opening the `*Python*` buffer,  get some strange characters and in the buffer. then when I hit return several times the buffer dies with the following message: 

`jupyter_console/ptshell.py:571: UserWarning: The kernel did not respond to an is_complete_request. Setting `use_kernel_is_complete` to Fal\
se.`

A full log of the `*Python*` console can be seen in this [gist](https://gist.github.com/pwt-nf/69ea13e775fc51d185eb703e3d0e0279).

Not sure if it matters but tell `elpy` to use `ipython` in `.emacs`:

`(elpy-enable)
(elpy-use-ipython)`

Thanks so much for this library, and thanks for any hints!

Peter

**Comment by gregsexton** [comment]
See #79 for explanation. I've just pushed a fix. Let me know if you're still having problems.
