### ISSUE TITLE
IPython 5 Prompt detection

### ISSUE THREAD

**Issue by salotz** [gregsexton/ob-ipython#89]
Just installed ob-python and I have the fancy new IPython prompt which I think is confusing things. When I execute a cell `C-c C-c` it starts the `*Python*` buffer which has the normal IPython `In [?]:` prompt but I get this warning 

```
Warning (emacs): Python shell prompts cannot be detected.
If your emacs session hangs when starting python shells
recover with `keyboard-quit' and then try fixing the
interactive flag for your interpreter by adjusting the
`python-shell-interpreter-interactive-arg' or add regexps
matching shell prompts in the directory-local friendly vars:
  + `python-shell-prompt-regexp'
  + `python-shell-prompt-block-regexp'
  + `python-shell-prompt-output-regexp'
Or alternatively in:
  + `python-shell-prompt-input-regexps'
  + `python-shell-prompt-output-regexps'
```

Nothing is hanging I don't think and I imagine it has something to do with this: https://github.com/gregsexton/ob-ipython/commit/cfdd9c00e6286d31d647defdb813b7aabfadcbff

I'm using version 20160918.1001 from MELPA, Jupyter 4.1.1, Jupyter console 5.0.0, IPython 5.1.0, and Python 3.5.2.

I'll try and install manually with that commit and see if that fixes it if I have time later.

**Comment by xin-jin** [comment]
I got the same warning message, though my simple script ran OK.

**Comment by pboynton** [comment]
The simple yet not so satisfying solution I found, thanks to [elpy issue 733](http://github.com/jorgenschaefer/elpy/issues/733), is to just get rid of the warning since I haven't found any issue with actually running my code. This command in .emacs will do it:

`(setq python-shell-prompt-detect-failure-warning nil)`

I tried the solution further down in that issue as well but it didn't work for me. I'm running Windows 10, Emacs 24.5.1, and using version 20160918.1001 of ob-ipython from MELPA as you are. This warning came up for the following 2 different Anaconda configurations, the first of which used Ipython 4 so it can't be related to Ipython 5 in particular.

- Jupyter 4.1.0, Jupyter console 4.1.1, IPython 4.2.0, and Python 2.7.11
- Jupyter 4.2.0, Jupyter console 5.0.0, IPython 5.1.0, and Python 2.7.12

It must have to do with the new version of ob-ipython because it only appeared right after I updated it on MELPA and it could be related to python-eldoc-setup-code as that is what seems to trigger the warning.

**Comment by deisi** [comment]
Hey I have the same, on windows 7 and python 3.5. For me this has the effect, that autocompletion doesn't work.

**Comment by salotz** [comment]
Recent updates to my emacs packages seem to have fixed my issue. It was probably a dependency as ob-ipython was not updated.

**Comment by deisi** [comment]
@salotz Do you run the git version or melpa

**Comment by salotz** [comment]
@deisi the Melpa one

**Comment by deisi** [comment]
Hmm I have the same one, and emacs was setup freshly on Monday, So 
updateing doesn't solve it for me then....

**Comment by salotz** [comment]
I am on Ubuntu 16.04 and one the updates for that might have done it as well. What emacs version are you using? I am on 24.5.1.

**Comment by pboynton** [comment]
I'm fully updated on MELPA and I'm still getting the warning. Could be updates on Ubuntu as you said.

**Comment by deisi** [comment]
I use Arch Linux and Windows.

I see the messages on both systems. emacs is 24.5.1 in both cases.

**Comment by salotz** [comment]
@deisi Are you just talking about autocompletion? Do you mean autocompletion in the org src buffer or at the ipython shell buffer? In any case that was not the original reason I started this issue.

**Comment by deisi** [comment]
@salotz I think the stuff with the auto-completion is kind of working now. (I don't really know for the windows machine, because I work in a VM at the moment). The problem was, that I didn't understand, one had to execute an ipython code-block first, before the auto completion feature becomes available. Now it is usually working as expected, though it often ops a new auto completion buffer instead of showing a drop-down table. Up to no I don't always fully understand what is going on, but I'm fairly knew to all this. I will see with time.
With all the different buffers and minor-modes involved, it can get quite confusing, why what is happening.

**Comment by deisi** [comment]
> In any case that was not the original reason I started this issue.
I know, it was rather meant as a side note. I am still experimenting 
with org-mode and ipython, and I was not sure what to
expect from the auto-completion feature. I'm used to jupiter notebooks 
and so I assumed it to "just work" by pressing tab, but apparently one 
has to get a bit used to it before it becomes easy. Anyway, we don't 
need to discuss this here. I will open an issue, when I can formulate 
the problem more precisely.

**Comment by jwhendy** [comment]
I'm also on arch linux here. I found that if I change `ob-ipython-command` from the default `"jupyter"` to `"ipython3"`, the mentioned warning goes away.

I'm using the git version, not melpa. Is this expected (I noticed there's another branch, so maybe I'm not using this correctly)?

```
$ emacs --version
GNU Emacs 25.2.1

$ python --version
Python 3.6.1

$ ipython3 --version
5.3.0

$ jupyter --version
4.3.0
```

Default process list when I get the warnings with `jupyter`::
```
Python          run     *Python*        /dev/pts/3   jupyter console --existing emacs-default.json
client-driver   run     *ob-ipython-... /dev/pts/1   /usr/bin/python -- /home/jwhendy/.elisp/ob-ipython/driver.py --port 9988
kernel-default  run     *ob-ipython-... /dev/pts/2   /usr/bin/python -- /home/jwhendy/.elisp/ob-ipython/driver.py --conn-file emacs-default.json
```

Process list with `ipython3` as command (no warnings):
```
Python          run     *Python*        /dev/pts/3   ipython3 console --existing emacs-default.json
client-driver   run     *ob-ipython-... /dev/pts/1   /usr/bin/python -- /home/jwhendy/.elisp/ob-ipython/driver.py --port 9988
kernel-default  run     *ob-ipython-... /dev/pts/2   /usr/bin/python -- /home/jwhendy/.elisp/ob-ipython/driver.py --conn-file emacs-default.json
```

Minimal config used with `emacs -Q` to test:
```
;; I get a warning about "symbol's value is void *" without this
;; see list of packages below
(package-initialize)

(add-to-list 'load-path "~/.elisp/org/lisp/")
(add-to-list 'load-path "~/.elisp/org/contrib/lisp")
(add-to-list 'load-path "~/.elisp/ess/lisp/")
(add-to-list 'load-path "~/.elisp/ob-ipython/")
(add-to-list 'load-path "~/.elisp/f.el/")
(add-to-list 'load-path "~/.elisp/s.el/")
(add-to-list 'load-path "~/.elisp/dash.el/")

(require 'org)

(require 'ob-ipython)
(setq ob-ipython-command "ipython3")

;; setup babel languages
(org-babel-do-load-languages
 'org-babel-load-languages
 '((ipython . t)))
```

I don't really use elpa, but it was the only way I managed to get `jedi` installed to try auto-completion. I get a warning if I don't run `(package-initialize)`, so I'm guessing that `ob-ipython` depends on something I have:
```
$ ls .emacs.d/elpa/
archives                     jedi-20160425.2156
auto-complete-20170124.1845  jedi-core-20170121.610
company-0.9.3                popup-20160709.729
concurrent-20161228.1930     python-environment-20150310.153
ctable-20140304.1659         pyvenv-1.10
deferred-20170331.1759       s-1.11.0
elpy-1.15.1                  yasnippet-0.11.0
epc-20140609.2234            company-0.9.3.signed
find-file-in-project-3.3     jedi-readme.txt
gnupg                        yasnippet-0.11.0.signed
highlight-indentation-0.6.0
```

**Comment by alastairdb** [comment]
My hack to get a usable REPL with IPython > 5:

```
diff --git a/ob-ipython.el b/ob-ipython.el
index d27c920..157b198 100644
--- a/ob-ipython.el
+++ b/ob-ipython.el
@@ -139,8 +139,16 @@
     (format "emacs-%s.json" name)))
 
 (defun ob-ipython--kernel-repl-cmd (name)
-  (list ob-ipython-command "console" "--existing"
-        (ob-ipython--kernel-file name)))
+  (with-temp-buffer
+    (call-process ob-ipython-command nil t nil "console" "--version")
+    (goto-char (point-max))
+    (forward-line -1)
+    (beginning-of-line)
+    (if (>= (string-to-number (char-to-string (char-after))) 5)
+	(list ob-ipython-command "console" "--simple-prompt" "--existing"
+	      (ob-ipython--kernel-file name))
+      (list ob-ipython-command "console" "--existing"
+	    (ob-ipython--kernel-file name)))))
 
 (defun ob-ipython--create-process (name cmd)
   (apply 'start-process name (format "*ob-ipython-%s*" name) (car cmd) (cdr cmd)))

```

**Comment by impaktor** [comment]
I'm experiencing the samme issue (also on Arch Linux), but this fixed it for me:
```emacs-lisp
(setq ob-ipython-command "ipython3")
```
But I do get deprecation warning that:
```
[TerminalIPythonApp] WARNING | Subcommand `ipython console` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter console` in the future
Jupyter console 6.0.0

Python 3.7.1 (default, Oct 22 2018, 10:41:28) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.1.1 -- An enhanced Interactive Python. Type '?' for help.
```

**Comment by salotz** [comment]
stale
