### ISSUE TITLE
Can't get a inline plot image

### ISSUE THREAD

**Issue by Retorz** [gregsexton/ob-ipython#92]
I tied all the code example in README, they are working fine.
But when I turned to some other example:

``` python
#+BEGIN_SRC ipython :session :exports both
  %matplotlib inline
  def top_counts(count_dict, n = 10):
      value_key_pairs = [(count, tz) for tz, count in count_dict.items()]
      value_key_pairs.sort()
      return value_key_pairs[-n:]

  frame = DataFrame(records)
  tz_counts = frame['tz'].value_counts()


  clean_tz = frame['tz'].fillna('missing')
  clean_tz[clean_tz == ''] = 'unknown'
  tz_counts = clean_tz.value_counts()
  tz_counts[:10].plot(kind = 'barh', rot = 0)
#+END_SRC

#+RESULTS:
: <matplotlib.figure.Figure at 0x1180f0990>
```

It did output a inline image as I expected, but when I change to `inferior python` buffer to execute the last command `tz_counts[:10].plot(kind = 'barh', rot = 0)` then the image prompt out. It's a little weird .

**Comment by ajsteven130** [comment]
normally you need to have a file tag in the `begin_src ipython...` line so that it is

 `begin_src ipython :session :file /tmp/image.png :exports both`

**Comment by concavegit** [comment]
reverting to this commit solved my problem: https://github.com/gregsexton/ob-ipython/commit/920f28322e2064c60889535f42d0aedf7d5d6d7a
